language: generic
os: linux
dist: trusty
compiler: g++
sudo: required
services: docker


before_script:
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  - git clone https://github.com/mypaint/mypaint.git
  #- bash ci/check_commit.sh master
  - 'if [ -e travis.cancel ]; then
        exit 0;
    fi'
  - travis_wait 120 sleep infinity & sudo docker pull photoflow/docker-trusty-appimage-base
  - sudo docker run -it -v $(pwd):/sources -e "GIT_BRANCH=master" centos:7 bash /sources/mkappimage.sh

after_success:
    - cd $TRAVIS_BUILD_DIR
    - pwd
    - ls -lh out/* # Assuming you have some files in out/ that you would like to upload
    #- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
    - bash  ./upload_rotate.sh "continuous" out/* >& /dev/null
    #- bash  ./upload_rotate.sh "continuous" $TRAVIS_BUILD_DIR/LuminanceHDR/commit-master.hash >& /dev/null

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

